name: "crucible-ci get benchmarks"
description: "Gets a list of benchmarks supported by crucible-ci"
inputs:
  runner-type:
    description: "What type of runner is this for (github, self, or all)?"
    required: true
outputs:
  benchmarks:
    description: "The list of supported benchmarks"
    value: ${{ steps.generate-benchmarks-list.outputs.benchmarks }}
runs:
  using: "composite"
  steps:
    - name: "Generate benchmarks list"
      id: generate-benchmarks-list
      shell: bash
      run: ${{ github.action_path }}/generate-benchmarks-list.sh ${{ inputs.runner-type }}
