name: "crucible-ci get endpoints"
description: "Gets a list of endpoints supported by crucible-ci"
inputs:
  runner-type:
    description: "What type of runner is this for (github, self, or all)?"
    required: true
outputs:
  endpoints:
    description: "The list of supported endpoints"
    value: ${{ steps.generate-endpoints-list.outputs.endpoints }}
runs:
  using: "composite"
  steps:
    - name: "Generate endpoints list"
      id: generate-endpoints-list
      shell: bash
      run: ${{ github.action_path }}/generate-endpoints-list.sh ${{ inputs.runner-type }}
