name: "install crucible"
description: "Install Crucible for use by various crucible-ci actions and/or workflows"
inputs:
  ci_target:
    description: "Which Crucible component to target for integration testing"
    required: false
    default: "none"
  ci_target_dir:
    description: "Where is the Crucible component to target located"
    required: false
    default: "none"
  ci_endpoint:
    description: "Which rickshaw endpoint to exercise"
    required: false
    default: "remotehost"
runs:
  using: "composite"
  steps:
    - run: sudo ${{ github.action_path }}/install-crucible.sh --run-environment github --ci-target ${{ inputs.ci_target }} --ci-target-dir ${{ inputs.ci_target_dir }} --ci-endpoint ${{ inputs.ci_endpoint }}
      shell: bash
