name: crucible-ci

on:
  # run on push or pull request events for the main branch only
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # allow for manual invocation from the actions tab
  workflow_dispatch:

jobs:
  crucible-ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: ./.github/actions/ci-environment-info

    - name: Setup CI Environment
      run: |
        sudo ./setup-ci-environment

    - name: Run CI
      run: |
        sudo ./run-ci --scenarios fio,uperf --userenvs all
