name: crucible-ci

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  generate-job-matrix-parameters:
    runs-on: ubuntu-latest

    outputs:
      userenvs: ${{ steps.get-userenvs.outputs.userenvs }}
      endpoints_github: ${{ steps.get-endpoints-github.outputs.endpoints }}
      endpoints_self: ${{ steps.get-endpoints-self.outputs.endpoints }}
      benchmarks_github: ${{ steps.get-benchmarks-github.outputs.benchmarks }}
      benchmarks_self: ${{ steps.get-benchmarks-self.outputs.benchmarks }}

    steps:
    - name: checkout crucible-ci
      uses: actions/checkout@v2
      with:
        path: crucible-ci

    - name: checkout rickshaw
      uses: actions/checkout@v2
      with:
        repository: perftool-incubator/rickshaw
        ref: master
        path: rickshaw

    - name: run get-userenvs
      id: get-userenvs
      uses: ./crucible-ci/.github/actions/get-userenvs
      with:
        rickshaw-directory: "./rickshaw"

    - name: run get-endpoints-github
      id: get-endpoints-github
      uses: ./crucible-ci/.github/actions/get-endpoints
      with:
        runner-type: "github"

    - name: run get-endpoints-self
      id: get-endpoints-self
      uses: ./crucible-ci/.github/actions/get-endpoints
      with:
        runner-type: "self"

    - name: run get-benchmarks-github
      id: get-benchmarks-github
      uses: ./crucible-ci/.github/actions/get-benchmarks
      with:
        runner-type: "github"

    - name: run get-benchmarks-self
      id: get-benchmarks-self
      uses: ./crucible-ci/.github/actions/get-benchmarks
      with:
        runner-type: "self"

  display-job-matrix-parameters:
    runs-on: ubuntu-latest

    needs: generate-job-matrix-parameters

    steps:
    - name: Echo generate-job-matrix-parameters outputs
      run: echo "${{ toJSON(needs.generate-job-matrix-parameters.outputs) }}"

  crucible-ci-github-runners:
    runs-on: ubuntu-latest
    needs:
    - generate-job-matrix-parameters
    - display-job-matrix-parameters
    continue-on-error: true
    strategy:
      matrix:
        endpoint: ${{ fromJSON(needs.generate-job-matrix-parameters.outputs.endpoints_github) }}
        benchmark: ${{ fromJSON(needs.generate-job-matrix-parameters.outputs.benchmarks_github) }}
        userenv: ${{ fromJSON(needs.generate-job-matrix-parameters.outputs.userenvs) }}
    steps:
    - name: Matrix Parameters => (${{ matrix.endpoint }}, ${{ matrix.benchmark }}, ${{ matrix.userenv }})
      run: |
        echo "endpoint=${{ matrix.endpoint }}"
        echo "benchmark=${{ matrix.benchmark }}"
        echo "userenv=${{ matrix.userenv }}"
    - name: checkout crucible-ci
      uses: actions/checkout@v2
    - name: run crucible-ci->integration-tests
      uses: ./.github/actions/integration-tests
      with:
        artifact_tag: "crucible-ci-github-runners__${{ matrix.endpoint }}-${{ matrix.benchmark }}-${{ matrix.userenv }}"
        ci_endpoint: "${{ matrix.endpoint }}"
        scenarios: "${{ matrix.benchmark }}"
        userenvs: "${{ matrix.userenv }}"
        run_samples: 3
        repeat_runs: "yes"

  crucible-ci-self-hosted-runners:
    runs-on: [ self-hosted ]
    needs:
    - generate-job-matrix-parameters
    - display-job-matrix-parameters
    continue-on-error: true
    strategy:
      matrix:
        endpoint: ${{ fromJSON(needs.generate-job-matrix-parameters.outputs.endpoints_self) }}
        benchmark: ${{ fromJSON(needs.generate-job-matrix-parameters.outputs.benchmarks_self) }}
        userenv: ${{ fromJSON(needs.generate-job-matrix-parameters.outputs.userenvs) }}
    steps:
    - name: Matrix Parameters => (${{ matrix.endpoint }}, ${{ matrix.benchmark }}, ${{ matrix.userenv }})
      run: |
        echo "endpoint=${{ matrix.endpoint }}"
        echo "benchmark=${{ matrix.benchmark }}"
        echo "userenv=${{ matrix.userenv }}"
    - name: checkout crucible-ci
      uses: actions/checkout@v2
    - name: run crucible-ci->integration-tests
      uses: ./.github/actions/integration-tests
      with:
        artifact_tag: "crucible-ci-self-hosted-runners__${{ matrix.endpoint }}-${{ matrix.benchmark }}-${{ matrix.userenv }}"
        ci_endpoint: "${{ matrix.endpoint }}"
        scenarios: "${{ matrix.benchmark }}"
        userenvs: "${{ matrix.userenv }}"
        run_samples: 3
        repeat_runs: "yes"

  crucible-ci-build-controller:
    runs-on: ubuntu-latest
    needs:
    - generate-job-matrix-parameters
    - display-job-matrix-parameters
    steps:
    - name: checkout crucible-ci
      uses: actions/checkout@v2
    - name: run crucible-ci->integration-tests
      uses: ./.github/actions/integration-tests
      with:
        artifact_tag: "build-controller"
        ci_build_controller: "yes"

  crucible-ci-complete:
    runs-on: ubuntu-latest
    needs:
    - crucible-ci-github-runners
    - crucible-ci-self-hosted-runners
    - crucible-ci-build-controller
    steps:
    - name: Confirm Success
      run: echo "crucible-ci-complete"
