name: crucible-ci

on:
  # run on push or pull request events for the main branch only
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # allow for manual invocation from the actions tab
  workflow_dispatch:

jobs:
  crucible-ci-all-userenvs-fio:
    name: crucible-ci-all-userenvs-fio

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: ./.github/actions/ci-environment-info

    - name: Setup CI Environment
      run: |
        sudo ./setup-ci-environment

    - name: Run fio CI
      run: |
        sudo ./run-ci --scenarios fio --userenvs all

    - name: Archive run data
      uses: actions/upload-artifact@v2
      with:
        name: crucible-ci-artifact-fio
        path: /var/lib/crucible-ci-artifact*.tar.xz
        retention-days: 5
        if-no-files-found: error

  crucible-ci-all-userenvs-uperf:
    name: crucible-ci-all-userenvs-uperf

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: ./.github/actions/ci-environment-info

    - name: Setup CI Environment
      run: |
        sudo ./setup-ci-environment

    - name: Run uperf CI
      run: |
        sudo ./run-ci --scenarios uperf --userenvs all

    - name: Archive run data
      uses: actions/upload-artifact@v2
      with:
        name: crucible-ci-artifact-uperf
        path: /var/lib/crucible-ci-artifact*.tar.xz
        retention-days: 5
        if-no-files-found: error
