name: crucible-ci

on:
  # run on pull request events for the main branch only
  pull_request:
    branches: [ main ]

  # allow for manual invocation from the actions tab
  workflow_dispatch:

jobs:
  crucible-ci-all-userenvs-fio-remotehost:
    name: crucible-ci-all-userenvs-fio-remotehost

    runs-on: ubuntu-latest

    steps:
    - name: checkout crucible-ci
      uses: actions/checkout@v2

    - name: run crucible-ci->integration-tests
      uses: ./.github/actions/integration-tests
      with:
        artifact_tag: "fio-remotehost"
        scenarios: "fio"
        userenvs: "all"
        ci_endpoint: "remotehost"

  crucible-ci-iteration-repeat-runs-fio-remotehost:
    name: crucible-ci-iteration-repeat-runs-fio-remotehost

    runs-on: ubuntu-latest

    steps:
    - name: checkout crucible-ci
      uses: actions/checkout@v2

    - name: run crucible-ci->integration-tests
      uses: ./.github/actions/integration-tests
      with:
        artifact_tag: "fio-iteration-repeat-runs-remotehost"
        scenarios: "fio"
        repeat_runs: "yes"
        ci_endpoint: "remotehost"

  crucible-ci-all-userenvs-fio-k8s:
    name: crucible-ci-all-userenvs-fio-k8s

    runs-on: ubuntu-latest

    steps:
    - name: checkout crucible-ci
      uses: actions/checkout@v2

    - name: run crucible-ci->integration-tests
      uses: ./.github/actions/integration-tests
      with:
        artifact_tag: "fio-k8s"
        scenarios: "fio"
        userenvs: "all"
        ci_endpoint: "k8s"

  crucible-ci-iteration-repeat-runs-fio-k8s:
    name: crucible-ci-iteration-repeat-runs-fio-k8s

    runs-on: ubuntu-latest

    steps:
    - name: checkout crucible-ci
      uses: actions/checkout@v2

    - name: run crucible-ci->integration-tests
      uses: ./.github/actions/integration-tests
      with:
        artifact_tag: "fio-iteration-repeat-runs-k8s"
        scenarios: "fio"
        repeat_runs: "yes"
        ci_endpoint: "k8s"

  crucible-ci-all-userenvs-uperf-remotehost:
    name: crucible-ci-all-userenvs-uperf-remotehost

    runs-on: ubuntu-latest

    steps:
    - name: checkout crucible-ci
      uses: actions/checkout@v2

    - name: run crucible-ci->integration-tests
      uses: ./.github/actions/integration-tests
      with:
        artifact_tag: "uperf-remotehost"
        scenarios: "uperf"
        userenvs: "all"
        ci_endpoint: "remotehost"

  crucible-ci-iteration-repeat-runs-uperf-remotehost:
    name: crucible-ci-iteration-repeat-runs-uperf-remotehost

    runs-on: ubuntu-latest

    steps:
    - name: checkout crucible-ci
      uses: actions/checkout@v2

    - name: run crucible-ci->integration-tests
      uses: ./.github/actions/integration-tests
      with:
        artifact_tag: "uperf-iteration-repeat-runs-remotehost"
        scenarios: "uperf"
        repeat_runs: "yes"
        ci_endpoint: "remotehost"

  crucible-ci-all-userenvs-uperf-k8s:
    name: crucible-ci-all-userenvs-uperf-k8s

    runs-on: ubuntu-latest

    steps:
    - name: checkout crucible-ci
      uses: actions/checkout@v2

    - name: run crucible-ci->integration-tests
      uses: ./.github/actions/integration-tests
      with:
        artifact_tag: "uperf-k8s"
        scenarios: "uperf"
        userenvs: "all"
        ci_endpoint: "k8s"

  crucible-ci-iteration-repeat-runs-uperf-k8s:
    name: crucible-ci-iteration-repeat-runs-uperf-k8s

    runs-on: ubuntu-latest

    steps:
    - name: checkout crucible-ci
      uses: actions/checkout@v2

    - name: run crucible-ci->integration-tests
      uses: ./.github/actions/integration-tests
      with:
        artifact_tag: "uperf-iteration-repeat-runs-k8s"
        scenarios: "uperf"
        repeat_runs: "yes"
        ci_endpoint: "k8s"

  crucible-ci-all-userenvs-iperf-remotehost:
    name: crucible-ci-all-userenvs-iperf-remotehost

    runs-on: ubuntu-latest

    steps:
    - name: checkout crucible-ci
      uses: actions/checkout@v2

    - name: run crucible-ci->integration-tests
      uses: ./.github/actions/integration-tests
      with:
        artifact_tag: "iperf-remotehost"
        scenarios: "iperf"
        userenvs: "all"
        ci_endpoint: "remotehost"

  crucible-ci-iteration-repeat-runs-iperf-remotehost:
    name: crucible-ci-iteration-repeat-runs-iperf-remotehost

    runs-on: ubuntu-latest

    steps:
    - name: checkout crucible-ci
      uses: actions/checkout@v2

    - name: run crucible-ci->integration-tests
      uses: ./.github/actions/integration-tests
      with:
        artifact_tag: "iperf-iteration-repeat-runs-remotehost"
        scenarios: "iperf"
        repeat_runs: "yes"
        ci_endpoint: "remotehost"

  crucible-ci-all-userenvs-iperf-k8s:
    name: crucible-ci-all-userenvs-iperf-k8s

    runs-on: ubuntu-latest

    steps:
    - name: checkout crucible-ci
      uses: actions/checkout@v2

    - name: run crucible-ci->integration-tests
      uses: ./.github/actions/integration-tests
      with:
        artifact_tag: "iperf-k8s"
        scenarios: "iperf"
        userenvs: "all"
        ci_endpoint: "k8s"

  crucible-ci-iteration-repeat-runs-iperf-k8s:
    name: crucible-ci-iteration-repeat-runs-iperf-k8s

    runs-on: ubuntu-latest

    steps:
    - name: checkout crucible-ci
      uses: actions/checkout@v2

    - name: run crucible-ci->integration-tests
      uses: ./.github/actions/integration-tests
      with:
        artifact_tag: "iperf-iteration-repeat-runs-k8s"
        scenarios: "iperf"
        repeat_runs: "yes"
        ci_endpoint: "k8s"
