name: faux-crucible-ci

on:
  pull_request:
    branches: [ main ]
    paths:
    - LICENSE
    - '**.md'
    - .github/workflows/faux-crucible-ci.yaml

jobs:
  crucible-ci-complete:
    runs-on: ubuntu-latest
    steps:
    - run: 'echo "No build required" '
